site_name: vanel

extra_css:
  - config/css/custom.css

theme:
  features:
    - navigation.path
  name: material 
  logo: config/images/logo.png
  favicon: config/images/logo.png
     
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


extra_javascript:
  - config/javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

